pipeline:
  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - ./csgo
    volumes:
      - /home/drone/cache:/cache

  download_game:
    image: fathosting/steamcmd:latest
    pull: true
    environment:
      - APP_NAME=csgo
      - APP_ID=740
    commands:
      - ./steamcmd.sh +login anonymous +force_install_dir $(pwd)/${APP_NAME} +app_update ${APP_ID} validate +quit

  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - ./csgo
    volumes:
      - /home/drone/cache:/cache

  publish:
    image: plugins/docker
    repo: fathosting/csgo
    tags: [ latest, ${DRONE_BRANCH} ]
    build_args:
      - APP_NAME=csgo
      - APP_ID=740
    when:
      event: tag

  notify:
    image: plugins/slack
    username: Drone
    template: >
      Build <{{build.link}}|{{repo.name}}#{{truncate build.commit 7}}> ({{build.branch}})
      by {{build.author}}
      finished with a *{{build.status}}* status
    when:
      status: [ success, failure ]
